# Generated by Django 5.0.7 on 2025-01-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('email_token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_validUser', models.BooleanField(default=False)),
                ('isGoogle', models.BooleanField(default=False)),
            ],
        ),
    ]
